### ISSUE TITLE
Create project documentation

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-app-circuit-maintenance#184]
### Environment

- Nautobot version: 
- nautobot-circuit-maintenance version: 0.5.0

### Proposed Functionality

Reorganize local docs and make them available locally in a side container, following internal dev-standards

### Use Case

Enhance documentation

**Comment by jvanderaa** [comment]
Would this also include the hosting of the docs on the `/static/` pages?

**Comment by chadell** [comment]
> Would this also include the hosting of the docs on the `/static/` pages?

yes

**Comment by chadell** [comment]
done
