### ISSUE TITLE
Job Creation: Search for Sites Without Redundant Circuit

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-app-circuit-maintenance#213]
### Environment

- Nautobot version: 
- nautobot-circuit-maintenance version: 

### Proposed Functionality

I'm looking to add a Nautobot Job to get packaged that will search through the possible records, and flag any sites that will not have a redundant circuit available during a maintenance of another circuit.

```
        # Query for all of the circuits maintenances that are on going in the future
        # Query for all of the circuits within Nautobot
        # Loop over each of the circuit maintenance records
            # Check to see if there are any circuit maintenances that are duplicated time
            # Report failures for any time where a circuit will take an outage
            # Evaluate adding a tag of an impeding site outage due to WAN outages
            # Log success for each time there is a known circuit still available at the site at the same time
```

### Use Case

Give the ability to notify when there is an outage being created by maintenance events, even though the network design has redundancy of circuits.

**Comment by chadell** [comment]
is this addressed by #214?
