### ISSUE TITLE
Add Prometheus metrics for the plugin

### ISSUE THREAD

**Issue by gertzakis** [nautobot/nautobot-app-circuit-maintenance#264]
### Environment

* Nautobot version:  ^1.5.13
* nautobot-circuit-maintenance version:  1.0.0

### Proposed Functionality

Expose different Prometheus metrics for circuit maintenance based on Nautobot's implementation for better monitoring. 

### Use Case
Some metrics as example are:

- Number of circuit maintenances that are on-going
- Number of circuit maintenance that needs acknowledgement
- Circuit maintenance per provider
- Circuit maintenance per circuit

**Comment by chadell** [comment]
same as #247
