### ISSUE TITLE
Add EWS API Notification source Support

### ISSUE THREAD

**Issue by Tibo-nauto** [nautobot/nautobot-app-circuit-maintenance#281]
### Environment
* Nautobot version:  2.1.1
* nautobot-circuit-maintenance version:  2.0.0

Ability to support EWS web API to receive email notifications from providers, such as IMAP or Gmail API.
https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/email-and-ews-in-exchange 

### Proposed Functionality

Pool mail with EWS API.

**Comment by TLCF** [comment]
Would be very useful given how common the EWS web API is used, even by non Microsoft systems in some cases.

**Comment by tlourey** [comment]
Would be very useful given how common the EWS web API is used, even by non Microsoft systems in some cases.
