### ISSUE TITLE
Wrong modelUrl for notificationsource

### ISSUE THREAD

**Issue by TitouanS31** [nautobot/nautobot-app-circuit-maintenance#313]
### Environment
* Python version:  3.11.9
* Nautobot version:  2.2.8
* nautobot-circuit-maintenance version:  2.2.3
* URL: https://demo.nautobot.com/

### Steps to Reproduce
1. Call OPTIONS method on the following endpoint: https://demo.nautobot.com/api/plugins/circuit-maintenance/rawnotification/
2. Take a look at the source `modelUrl`

### Expected Behavior
The `modelUrl` for notification sources matches the endpoint URL.
`"modelUrl": "/plugins/circuit-maintenance/notificationsource/"`

### Observed Behavior
`"modelUrl": "/plugins/circuit-maintenance/source/"`

**Comment by chadell** [comment]
solve in #320 , it will come in a next major release because it's a breaking change
